<a href="https://colab.research.google.com/github/Shambhuraje1919/Generative-AI/blob/main/autogen_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U "autogen-agentchat" "autogen-ext[openai]"

In [33]:
import os

os.environ["GROQ_API_KEY"] = "#############"

In [5]:
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_agentchat.agents import AssistantAgent

In [27]:
model_client = OpenAIChatCompletionClient(
    model = "openai/gpt-oss-20b" ,
    api_key = os.environ["GROQ_API_KEY"],
    base_url="https://api.groq.com/openai/v1",
    model_info={
        "vision": False,
        "function_calling": True,
        "json_output": True,
        "family": "unknown",
        "structured_output": False
    }

)

In [28]:
model_client

In [30]:
agent = AssistantAgent(
    model_client=model_client,
    name = 'Assisatant'
)

In [31]:
agent

In [32]:
res = await agent.run(
    task = ' who is pm of india'
)
print(res)

messages=[TextMessage(id='036cf1b1-9699-4bf0-932f-10243a41e23b', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2026, 8, 20, 13, 36, 41, 971055, tzinfo=datetime.timezone.utc), content=' who is pm of india', type='TextMessage'), TextMessage(id='2ed0ac43-127d-486a-a9a6-dc2d41978ee0', source='Assisatant', models_usage=RequestUsage(prompt_tokens=104, completion_tokens=48), metadata={}, created_at=datetime.datetime(2026, 8, 20, 13, 36, 42, 186759, tzinfo=datetime.timezone.utc), content='The current Prime Minister of India is Narendra Modi.  \nTERMINATE', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='036cf1b1-9699-4bf0-932f-10243a41e23b', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2026, 8, 20, 13, 36, 41, 971055, tzinfo=datetime.timezone.utc), content=' who is pm of india', type='TextMessage'), TextMessage(id='2ed0ac43-127d-486a-a9a6-dc2d41978ee0', source='Assisatant', models_usage=RequestUsage(prompt_tokens=104, completion_tokens=48), metadata={}, created_at=datetime.datetime(2026, 8, 20, 13, 36, 42, 186759, tzinfo=datetime.timezone.utc), content='The current Prime Minister of India is Narendra Modi.  \nTERMINATE', type='TextMessage')] stop_reason=None

